"""HTML page routes and htmx fragment routes.

Page routes render full-page templates; fragment routes return partial
HTML for htmx swaps. No business logic lives here — pages call the
same DB queries that the JSON API already exposes, and fragments are
thin slices of the same data shaped for incremental DOM updates.
"""

import json
from pathlib import Path

from fastapi import APIRouter, Depends, Request
from fastapi.templating import Jinja2Templates
from sqlalchemy import select
from sqlalchemy.orm import Session

from app import config
from app.database import get_db
from app.models import Device, Schedule
from app.schemas import DeviceRead, ScheduleRead

router = APIRouter(tags=["pages"])
templates = Jinja2Templates(directory="app/templates")


def _format_days_of_week(bitmask: int) -> str:
    if bitmask == 127:
        return "Every day"
    if bitmask == 0b0011111:
        return "Weekdays"
    if bitmask == 0b1100000:
        return "Weekends"
    names = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
    days = [name for i, name in enumerate(names) if bitmask & (1 << i)]
    return ", ".join(days) if days else "Never"


def _format_time_of_day(t) -> str:
    hour = t.hour
    minute = f"{t.minute:02d}"
    period = "PM" if hour >= 12 else "AM"
    hour = hour % 12 or 12
    return f"{hour}:{minute} {period}"


def _format_sun_offset(trigger_type: str, offset_minutes: int | None) -> str:
    label = "Sunrise" if trigger_type == "sunrise" else "Sunset"
    if not offset_minutes:
        return label
    sign = "+" if offset_minutes > 0 else "-"
    return f"{label} {sign}{abs(offset_minutes)}m"


# SVG strings for every icon key that can be stored on a Device or Schedule.
# Loaded from lucide_icons.json, which is generated by scripts/generate-icons.js
# and committed to the repo alongside icons.js. Falls back to an empty dict so
# the app starts even if someone skips the generation step (icons just won't
# render server-side until the file exists).
_LUCIDE_JSON = Path(__file__).parent.parent / "lucide_icons.json"
PICKER_ICON_SVGS: dict[str, str] = (
    json.loads(_LUCIDE_JSON.read_text()) if _LUCIDE_JSON.exists() else {}
)

templates.env.globals.update(
    format_days_of_week=_format_days_of_week,
    format_time_of_day=_format_time_of_day,
    format_sun_offset=_format_sun_offset,
    picker_icon_svgs=PICKER_ICON_SVGS,
)


def _device_reads(db: Session, sort: str = "name") -> list[DeviceRead]:
    """Fetch all devices and compute the derived `online` field via the
    schema. Sorting by status puts online devices first (then by name);
    everything else sorts by name only."""
    rows = list(db.execute(select(Device)).scalars())
    reads = [DeviceRead.model_validate(d) for d in rows]
    if sort == "status":
        reads.sort(key=lambda d: (not d.online, d.name.lower()))
    else:
        reads.sort(key=lambda d: d.name.lower())
    return reads


def _schedule_reads(
    db: Session, status_filter: str = "all", device_id: str | None = None
) -> list[ScheduleRead]:
    stmt = select(Schedule).order_by(Schedule.name)
    if device_id is not None:
        stmt = stmt.where(Schedule.device_id == device_id)
    rows = list(db.execute(stmt).scalars())
    reads = [ScheduleRead.model_validate(s) for s in rows]
    if status_filter == "active":
        reads = [s for s in reads if s.enabled]
    elif status_filter == "inactive":
        reads = [s for s in reads if not s.enabled]
    elif status_filter == "sun":
        reads = [s for s in reads if s.trigger_type.value in ("sunrise", "sunset")]
    return reads


# ---------------------------------------------------------------------------
# Full-page routes
# ---------------------------------------------------------------------------


@router.get("/")
def index(request: Request, db: Session = Depends(get_db)):
    schedules = _schedule_reads(db)
    return templates.TemplateResponse(
        request, "schedules.html",
        {"active_page": "schedules", "schedules": schedules, "device_id": None},
    )


@router.get("/devices")
def devices_page(request: Request, db: Session = Depends(get_db)):
    devices = _device_reads(db)
    return templates.TemplateResponse(
        request, "devices.html", {"active_page": "devices", "devices": devices}
    )


@router.get("/devices/{device_id}")
def device_detail_page(request: Request, device_id: str):
    return templates.TemplateResponse(
        request, "device_detail.html", {"active_page": "devices", "device_id": device_id}
    )


@router.get("/history")
def history_overview_page(request: Request):
    return templates.TemplateResponse(
        request, "history.html", {"active_page": "history", "schedule_id": None}
    )


@router.get("/settings")
def settings_page(request: Request):
    return templates.TemplateResponse(
        request, "settings.html", {"active_page": "settings", "app_version": config.APP_VERSION}
    )


@router.get("/schedules")
def schedules_page(
    request: Request, device_id: str | None = None, db: Session = Depends(get_db)
):
    schedules = _schedule_reads(db, device_id=device_id)
    return templates.TemplateResponse(
        request, "schedules.html",
        {"active_page": "schedules", "schedules": schedules, "device_id": device_id},
    )


@router.get("/schedules/new")
def schedule_new_page(request: Request):
    return templates.TemplateResponse(
        request, "schedule_form.html", {"active_page": "schedules", "schedule_id": None}
    )


@router.get("/schedules/{schedule_id}/edit")
def schedule_edit_page(request: Request, schedule_id: str):
    return templates.TemplateResponse(
        request, "schedule_form.html", {"active_page": "schedules", "schedule_id": schedule_id}
    )


@router.get("/schedules/{schedule_id}/history")
def schedule_history_page(request: Request, schedule_id: str):
    return templates.TemplateResponse(
        request, "history.html", {"active_page": "schedules", "schedule_id": schedule_id}
    )


# ---------------------------------------------------------------------------
# htmx fragment routes
# ---------------------------------------------------------------------------


@router.get("/fragments/devices/list")
def devices_list_fragment(
    request: Request, sort: str = "name", db: Session = Depends(get_db)
):
    """Device rows only, for the sort-select hx-get swap. Includes
    OOB updates for stats and the systems card so one request keeps
    everything consistent."""
    devices = _device_reads(db, sort)
    return templates.TemplateResponse(
        request, "fragments/devices_list.html", {"devices": devices}
    )


@router.get("/fragments/devices/statuses")
def devices_statuses_fragment(request: Request, db: Session = Depends(get_db)):
    """Pure OOB payload — no main-swap content. Used by the 15-second
    hx-trigger polling element on the devices page to update badges,
    icons, and stats counters without touching the rest of the DOM."""
    devices = _device_reads(db)
    return templates.TemplateResponse(
        request, "fragments/devices_statuses.html", {"devices": devices}
    )


@router.get("/fragments/schedules/list")
def schedules_list_fragment(
    request: Request,
    filter: str = "all",  # noqa: A002
    device_id: str | None = None,
    db: Session = Depends(get_db),
):
    schedules = _schedule_reads(db, filter, device_id)
    return templates.TemplateResponse(
        request, "fragments/schedules_list.html",
        {"schedules": schedules, "filter": filter, "device_id": device_id},
    )
