"""HTML page routes and htmx fragment routes.

Page routes render full-page templates; fragment routes return partial
HTML for htmx swaps. No business logic lives here — pages call the
same DB queries that the JSON API already exposes, and fragments are
thin slices of the same data shaped for incremental DOM updates.
"""

import json
import socket
from datetime import datetime, timedelta, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

from fastapi import APIRouter, Depends, Request
from fastapi.templating import Jinja2Templates
from sqlalchemy import func, select
from sqlalchemy.orm import Session

from app import config
from app.database import get_db
from app.models import Device, Schedule, ScheduleExecution, Settings
from app.schemas import DeviceRead, ScheduleRead
from app.view_helpers import (
    get_device_reads,
    get_history_execution_rows,
    get_schedule_reads,
    load_devices_by_id,
)

router = APIRouter(tags=["pages"])
templates = Jinja2Templates(directory="app/templates")


def _format_days_of_week(bitmask: int) -> str:
    if bitmask == 127:
        return "Every day"
    if bitmask == 0b0011111:
        return "Weekdays"
    if bitmask == 0b1100000:
        return "Weekends"
    names = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
    days = [name for i, name in enumerate(names) if bitmask & (1 << i)]
    return ", ".join(days) if days else "Never"


def _format_time_of_day(t) -> str:
    hour = t.hour
    minute = f"{t.minute:02d}"
    period = "PM" if hour >= 12 else "AM"
    hour = hour % 12 or 12
    return f"{hour}:{minute} {period}"


def _format_sun_offset(trigger_type: str, offset_minutes: int | None) -> str:
    label = "Sunrise" if trigger_type == "sunrise" else "Sunset"
    if not offset_minutes:
        return label
    sign = "+" if offset_minutes > 0 else "-"
    return f"{label} {sign}{abs(offset_minutes)}m"


# SVG strings for every icon key that can be stored on a Device or Schedule.
# Loaded from lucide_icons.json, which is generated by scripts/generate-icons.js
# and committed to the repo alongside icons.js. Falls back to an empty dict so
# the app starts even if someone skips the generation step (icons just won't
# render server-side until the file exists).
_LUCIDE_JSON = Path(__file__).parent.parent / "lucide_icons.json"
PICKER_ICON_SVGS: dict[str, str] = (
    json.loads(_LUCIDE_JSON.read_text()) if _LUCIDE_JSON.exists() else {}
)

templates.env.globals.update(
    format_days_of_week=_format_days_of_week,
    format_time_of_day=_format_time_of_day,
    format_sun_offset=_format_sun_offset,
    picker_icon_svgs=PICKER_ICON_SVGS,
)

# SVGs for status-based fallback icons in history (matches historyIcon() in icons.js).
_HISTORY_FALLBACK_SVG = {
    "success": '<svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5" /> <path d="M9 18h6" /> <path d="M10 22h4" /></svg>',
    "failed":  '<svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3" /> <path d="M12 9v4" /> <path d="M12 17h.01" /></svg>',
    "skipped": '<svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><polygon points="5 4 15 12 5 20 5 4" /> <line x1="19" x2="19" y1="5" y2="19" /></svg>',
    "partial": '<svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9" /> <path d="M12 8v4" /> <path d="M12 16h.01" /></svg>',
}
_HISTORY_STATUS_CLASS = {
    "success": "icon-avatar--sun",
    "failed":  "icon-avatar--danger",
    "skipped": "icon-avatar--moon",
    "partial": "icon-avatar--warning",
}
_HISTORY_STATUS_LABEL = {
    "success": "Successful", "failed": "Failed", "skipped": "Skipped", "partial": "Partial",
}
_HISTORY_STATUS_COLOR = {
    "success": "var(--success)",
    "failed":  "var(--danger)",
    "skipped": "var(--text-muted)",
    "partial": "var(--amber)",
}
_PAGE_SIZE = 20


def _history_action_label(action) -> str:
    if action.type.value == "preset":
        n = action.payload.get("n")
        return n if n else f"Preset #{action.payload.get('ps', '?')}"
    if action.payload.get("on") is False:
        return "Turn Off"
    return "Turn On"


def _history_group_label(d, today) -> str:
    from datetime import date as date_type, timedelta
    if d == today:
        return f"Today — {d.strftime('%B %-d, %Y')}"
    if d == today - timedelta(days=1):
        return f"Yesterday — {d.strftime('%B %-d, %Y')}"
    return d.strftime('%B %-d, %Y')


def _prepare_history(
    db: Session,
    executions: list,
    tz,
    today,
) -> list[dict]:
    """Convert raw ScheduleExecution ORM rows into flat dicts ready for the
    history fragment template — all formatting resolved here so the template
    stays dumb. One dict per execution (not per device); each carries a
    device_results list for the per-device breakdown within that row."""
    devices_by_id = load_devices_by_id(
        db, {r["device_id"] for e in executions for r in e.device_results}
    )

    result = []
    for e in executions:
        dt_utc = e.fired_at.replace(tzinfo=timezone.utc)
        local_dt = dt_utc.astimezone(tz)
        hour = local_dt.hour
        time_str = f"{hour % 12 or 12}:{local_dt.minute:02d} {'PM' if hour >= 12 else 'AM'}"

        action_str = _history_action_label(e.schedule.action)
        overall = e.overall_status
        sched_icon = PICKER_ICON_SVGS.get(e.schedule.icon) if e.schedule.icon else None

        device_results = []
        for r in e.device_results:
            device = devices_by_id.get(r["device_id"])
            status = r["status"]
            device_results.append({
                "device_name": device.name if device else "Deleted device",
                "device_icon_svg": (
                    PICKER_ICON_SVGS.get(device.icon) if device and device.icon else None
                ),
                "device_id": device.id if device else None,
                "status_label": _HISTORY_STATUS_LABEL[status],
                "status_color": _HISTORY_STATUS_COLOR[status],
                "error_message": r.get("error_message"),
            })

        result.append({
            "local_date": local_dt.date(),
            "time_str": time_str,
            "schedule_name": e.schedule.name,
            "action_str": action_str,
            "status_label": _HISTORY_STATUS_LABEL[overall],
            "status_color": _HISTORY_STATUS_COLOR[overall],
            "status_class": _HISTORY_STATUS_CLASS[overall],
            "avatar_svg": sched_icon or _HISTORY_FALLBACK_SVG[overall],
            "device_results": device_results,
        })
    return result



def _device_reads(db: Session, sort: str = "name") -> list[DeviceRead]:
    """Backward-compatible wrapper around the shared view helper."""
    return get_device_reads(db, sort)


def _schedule_reads(
    db: Session, status_filter: str = "all", device_id: str | None = None
) -> list[ScheduleRead]:
    return get_schedule_reads(db, status_filter, device_id)


# ---------------------------------------------------------------------------
# Full-page routes
# ---------------------------------------------------------------------------


@router.get("/")
def index(request: Request, db: Session = Depends(get_db)):
    schedules = _schedule_reads(db)
    devices = list(db.execute(select(Device).order_by(Device.name)).scalars())
    return templates.TemplateResponse(
        request, "schedules.html",
        {"active_page": "schedules", "schedules": schedules, "devices": devices, "device_id": None},
    )


@router.get("/devices")
def devices_page(request: Request, db: Session = Depends(get_db)):
    devices = _device_reads(db)
    return templates.TemplateResponse(
        request, "devices.html", {"active_page": "devices", "devices": devices}
    )


@router.get("/devices/{device_id}")
def device_detail_page(request: Request, device_id: str):
    return templates.TemplateResponse(
        request, "device_detail.html", {"active_page": "devices", "device_id": device_id}
    )


@router.get("/history")
def history_overview_page(
    request: Request, device_id: str | None = None, db: Session = Depends(get_db)
):
    devices = list(db.execute(select(Device).order_by(Device.name)).scalars())
    return templates.TemplateResponse(
        request, "history.html",
        {"active_page": "history", "devices": devices, "device_id": device_id},
    )


def _get_network_info() -> dict:
    hostname = socket.gethostname()
    try:
        # UDP connect trick: determines the outbound interface IP without
        # actually sending any packets. More reliable than gethostbyname()
        # which often returns 127.0.0.1 on systems with a loopback hostname.
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.settimeout(0)
        s.connect(("10.254.254.254", 1))
        ip: str | None = s.getsockname()[0]
        s.close()
    except Exception:
        ip = None
    return {"hostname": hostname, "local_hostname": f"{hostname}.local", "ip": ip}


def _get_last_backup() -> str | None:
    backup_dir = Path(config.DATABASE_PATH).parent / "backups"
    if not backup_dir.exists():
        return None
    backups = sorted(backup_dir.glob("scheduler_*.db"), key=lambda p: p.name, reverse=True)
    if not backups:
        return None
    stem = backups[0].stem  # scheduler_YYYYMMDD_HHMMSS
    ts = stem[len("scheduler_"):]  # YYYYMMDD_HHMMSS
    try:
        return f"{ts[0:4]}-{ts[4:6]}-{ts[6:8]} {ts[9:11]}:{ts[11:13]}:{ts[13:15]}"
    except Exception:
        return backups[0].name


def _resolve_display_tz(db: Session):
    """The configured timezone if Settings has one, otherwise UTC.
    Shared by anything rendering a server-side timestamp for display,
    same fallback behavior as the history fragment always used."""
    settings = db.get(Settings, 1)
    try:
        return ZoneInfo(settings.timezone) if settings and settings.timezone else timezone.utc
    except Exception:
        return timezone.utc


def _format_uptime(delta: timedelta) -> str:
    total_seconds = int(delta.total_seconds())
    days, rem = divmod(total_seconds, 86400)
    hours, rem = divmod(rem, 3600)
    minutes, _ = divmod(rem, 60)
    if days:
        return f"{days}d {hours}h {minutes}m"
    if hours:
        return f"{hours}h {minutes}m"
    return f"{minutes}m"


def _get_system_info(db: Session) -> dict:
    """Pulled together from what the running process already knows
    about itself: package metadata and the clock. Deliberately nothing
    here needs host-level access from inside the container (Docker's
    own version, host uptime, etc aren't available without mounting
    the Docker socket, a separate, unresolved constraint, not
    something to quietly work around here)."""
    now = datetime.now(timezone.utc)
    tz = _resolve_display_tz(db)
    return {
        "version": config.APP_VERSION,
        "uptime": _format_uptime(now - config.START_TIME),
        "started_at": config.START_TIME.astimezone(tz).strftime("%B %-d, %Y %-I:%M %p"),
    }


@router.get("/settings")
def settings_page(request: Request, db: Session = Depends(get_db)):
    return templates.TemplateResponse(
        request, "settings.html", {
            "active_page": "settings",
            "network": _get_network_info(),
            "last_backup": _get_last_backup(),
            "system": _get_system_info(db),
        }
    )


@router.get("/schedules")
def schedules_page(
    request: Request, device_id: str | None = None, db: Session = Depends(get_db)
):
    schedules = _schedule_reads(db, device_id=device_id)
    devices = list(db.execute(select(Device).order_by(Device.name)).scalars())
    return templates.TemplateResponse(
        request, "schedules.html",
        {"active_page": "schedules", "schedules": schedules, "devices": devices, "device_id": device_id},
    )


@router.get("/schedules/new")
def schedule_new_page(request: Request):
    return templates.TemplateResponse(
        request, "schedule_form.html", {"active_page": "schedules", "schedule_id": None}
    )


@router.get("/schedules/{schedule_id}/edit")
def schedule_edit_page(request: Request, schedule_id: str):
    return templates.TemplateResponse(
        request, "schedule_form.html", {"active_page": "schedules", "schedule_id": schedule_id}
    )


@router.get("/schedules/{schedule_id}/history")
def schedule_history_page(
    request: Request, schedule_id: str, db: Session = Depends(get_db)
):
    devices = list(db.execute(select(Device).order_by(Device.name)).scalars())
    return templates.TemplateResponse(
        request, "history.html",
        {"active_page": "schedules", "devices": devices, "device_id": None},
    )


# ---------------------------------------------------------------------------
# htmx fragment routes
# ---------------------------------------------------------------------------


@router.get("/fragments/devices/list")
def devices_list_fragment(
    request: Request, sort: str = "name", db: Session = Depends(get_db)
):
    """Device rows only, for the sort-select hx-get swap. Includes
    OOB updates for stats and the systems card so one request keeps
    everything consistent."""
    devices = _device_reads(db, sort)
    return templates.TemplateResponse(
        request, "fragments/devices_list.html", {"devices": devices}
    )


@router.get("/fragments/devices/statuses")
def devices_statuses_fragment(request: Request, db: Session = Depends(get_db)):
    """Pure OOB payload — no main-swap content. Used by the 15-second
    hx-trigger polling element on the devices page to update badges,
    icons, and stats counters without touching the rest of the DOM."""
    devices = _device_reads(db)
    return templates.TemplateResponse(
        request, "fragments/devices_statuses.html", {"devices": devices}
    )


@router.get("/fragments/schedules/list")
def schedules_list_fragment(
    request: Request,
    filter: str = "all",  # noqa: A002
    device_id: str | None = None,
    db: Session = Depends(get_db),
):
    schedules = _schedule_reads(db, filter, device_id)
    return templates.TemplateResponse(
        request, "fragments/schedules_list.html",
        {"schedules": schedules, "filter": filter, "device_id": device_id},
    )


@router.get("/fragments/history/entries")
def history_entries_fragment(
    request: Request,
    device_id: str | None = None,
    since: str = "7",
    offset: int = 0,
    db: Session = Depends(get_db),
):
    tz = _resolve_display_tz(db)
    now_utc = datetime.now(timezone.utc)
    today = now_utc.astimezone(tz).date()

    rows = get_history_execution_rows(
        db,
        device_id=device_id,
        since=since,
        offset=offset,
        limit=_PAGE_SIZE,
        now_utc=now_utc,
    )
    has_more = len(rows) > _PAGE_SIZE
    rows = rows[:_PAGE_SIZE]

    entries = _prepare_history(db, rows, tz, today)

    # Group by local date, preserving order.
    groups: dict = {}
    for entry in entries:
        d = entry["local_date"]
        if d not in groups:
            groups[d] = []
        groups[d].append(entry)

    return templates.TemplateResponse(
        request, "fragments/history_entries.html",
        {
            "groups": groups,
            "today": today,
            "group_label": _history_group_label,
            "new_offset": offset + len(entries),
            "has_more": has_more,
            "is_first_page": offset == 0,
            "device_id": device_id,
            "since": since,
        },
    )
