"""add_icon_to_devices_and_schedules

Revision ID: bf72ce13d420
Revises: d4e7f1a2b3c9
Create Date: 2026-06-28 10:55:13.258659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf72ce13d420'
down_revision: Union[str, Sequence[str], None] = 'd4e7f1a2b3c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=50), nullable=True))

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_column('icon')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
