"""initial schema

Revision ID: e52f713d398e
Revises: 
Create Date: 2026-06-25 01:52:16.108813

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e52f713d398e'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('preset', 'state', name='actiontype'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('transition_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('mac', sa.String(length=20), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('catch_up_missed', sa.Boolean(), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_settings_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('trigger_type', sa.Enum('time', 'sunrise', 'sunset', name='triggertype'), nullable=False),
    sa.Column('time_of_day', sa.Time(), nullable=True),
    sa.Column('offset_minutes', sa.Integer(), nullable=True),
    sa.Column('days_of_week', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(trigger_type != 'time') OR (time_of_day IS NOT NULL)", name='ck_schedule_time_requires_time_of_day'),
    sa.CheckConstraint("(trigger_type = 'time') OR (offset_minutes IS NOT NULL)", name='ck_schedule_sun_requires_offset'),
    sa.CheckConstraint('days_of_week >= 0 AND days_of_week <= 127', name='ck_schedule_days_of_week_range'),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index('ix_schedules_action_id', ['action_id'], unique=False)
        batch_op.create_index('ix_schedules_device_id', ['device_id'], unique=False)
        batch_op.create_index('ix_schedules_next_run_at', ['next_run_at'], unique=False)

    op.create_table('schedule_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('schedule_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('fired_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', name='executionstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_executions', schema=None) as batch_op:
        batch_op.create_index('ix_schedule_executions_fired_at', ['fired_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_executions', schema=None) as batch_op:
        batch_op.drop_index('ix_schedule_executions_fired_at')

    op.drop_table('schedule_executions')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index('ix_schedules_next_run_at')
        batch_op.drop_index('ix_schedules_device_id')
        batch_op.drop_index('ix_schedules_action_id')

    op.drop_table('schedules')
    op.drop_table('settings')
    op.drop_table('devices')
    op.drop_table('actions')
    # ### end Alembic commands ###
